/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package career_guidance_app;

/**
 *
 * @author shiva
 */
public class ALL_CAREER_FIELDS extends javax.swing.JFrame {

    /**
     * Creates new form ALL_CAREER_FIELDS
     */
    public ALL_CAREER_FIELDS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cmbletter = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblshow = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(198, 83));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 182, 163));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All Career Options in India");

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 0));
        jButton1.setText("GET CAREER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbletter.setBackground(new java.awt.Color(0, 102, 255));
        cmbletter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbletter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));
        cmbletter.setToolTipText("");

        jScrollPane1.setBackground(new java.awt.Color(0, 204, 153));

        lblshow.setBackground(new java.awt.Color(0, 204, 153));
        lblshow.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lblshow.setForeground(new java.awt.Color(153, 0, 153));
        lblshow.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        lblshow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(lblshow);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setText("....");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(cmbletter, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbletter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String letter=(String) cmbletter.getSelectedItem();
        if (letter.equals("A")) {
            lblshow.setText("""
                            <html>A<br>
                            \u203a\u203a\tAccountancy<br>
                            \u203a\u203a\tActuarial Science<br>
                            \u203a\u203a\tAcupressure Therapy<br>
                            \u203a\u203a\tAcupuncture<br>
                            \u203a\u203a\tAdventure Sports<br>
                            \u203a\u203a\tAdventure Tourism<br>
                            \u203a\u203a\tAdvertising<br>
                            \u203a\u203a\tAdvocate General<br>
                            \u203a\u203a\tAeronautical Engineering<br>
                            \u203a\u203a\tAgricultural Economics<br>
                            \u203a\u203a\tAgricultural Engineering<br>
                            \u203a\u203a\tAgricultural Science<br>
                            \u203a\u203a\tAgronomist<br>
                            \u203a\u203a\tAir Hostess Training<br>
                            \u203a\u203a\tAir Traffic Control<br>
                            \u203a\u203a\tAnchoring<br>
                            \u203a\u203a\tAnesthesiology<br>
                            \u203a\u203a\tAnimal Training<br>
                            \u203a\u203a\tAnimation<br>
                            \u203a\u203a\tAnthropology<br>
                            \u203a\u203a\tAqua Culture<br>
                            \u203a\u203a\tArchaeology<br>
                            \u203a\u203a\tArchitectural Engineering<br>
                            \u203a\u203a\tArchival Science<br>
                            \u203a\u203a\tAromatherapy<br>
                            \u203a\u203a\tAssistant District Attorney<br>
                            \u203a\u203a\tAstronomy<br>
                            \u203a\u203a\tAttorney General<br>
                            \u203a\u203a\tAudio Engineering<br>
                            \u203a\u203a\tAuditing<br>
                            \u203a\u203a\tAutomobile Engineering<br>
                            \u203a\u203a\tAyurveda</html>""");
        }else if (letter.equals("B")) {
            lblshow.setText("""
                            <html>B<br>
                            \u203a\u203a\tBaking<br>
                            \u203a\u203a\tBanking<br>
                            \u203a\u203a\tBartending<br>
                            \u203a\u203a\tBeauty Care<br>
                            \u203a\u203a\tBehavioral Science<br>
                            \u203a\u203a\tBiochemistry<br>
                            \u203a\u203a\tBioinformatics<br>
                            \u203a\u203a\tBiomedical Engineering<br>
                            \u203a\u203a\tBiophysics<br>
                            \u203a\u203a\tBiotechnology<br>
                            \u203a\u203a\tBody Guard/ Security Officer<br>
                            \u203a\u203a\tBook Publishing<br>
                            \u203a\u203a\tBorder Security Force (BSF)<br>
                            \u203a\u203a\tBotany<br>
                            \u203a\u203a\tBrand Management<br>
                            \u203a\u203a\tBroadcast Engineering<br>
                            \u203a\u203a\tBusiness Administration</html>""");
        }else if (letter.equals("C")) {
            lblshow.setText("""
                            <html>C<br>
                            \u203a\u203a\tCall Centers<br>
                            \u203a\u203a\tCalligraphy<br>
                            \u203a\u203a\tCardiology<br>
                            \u203a\u203a\tCartography<br>
                            \u203a\u203a\tCatering Service<br>
                            \u203a\u203a\tCBI Officer<br>
                            \u203a\u203a\tCentral Industrial Security Force (CISF)<br>
                            \u203a\u203a\tCentral Reserve Police Force (CRPF)<br>
                            \u203a\u203a\tCeramic Engineering<br>
                            \u203a\u203a\tChartered Accountancy<br>
                            \u203a\u203a\tChef<br>
                            \u203a\u203a\tChemical Engineering<br>
                            \u203a\u203a\tChemistry<br>
                            \u203a\u203a\tChocolatier<br>
                            \u203a\u203a\tChromo Therapy<br>
                            \u203a\u203a\tCID Officer<br>
                            \u203a\u203a\tCinematography<br>
                            \u203a\u203a\tCivil Engineering<br>
                            \u203a\u203a\tCivil Service<br>
                            \u203a\u203a\tClinical Research<br>
                            \u203a\u203a\tCloud Computing<br>
                            \u203a\u203a\tCommercial Pilot<br>
                            \u203a\u203a\tCompany Secretary<br>
                            \u203a\u203a\tComputer Aided Design (CAD)<br>
                            \u203a\u203a\tComputer Engineering<br>
                            \u203a\u203a\tComputer Networking<br>
                            \u203a\u203a\tComputer Systems Analyst<br>
                            \u203a\u203a\tCorporate Communication<br>
                            \u203a\u203a\tCorporate Training<br>
                            \u203a\u203a\tCosmetology<br>
                            \u203a\u203a\tCounselling<br>
                            \u203a\u203a\tCreative Writing<br>
                            \u203a\u203a\tCriminology<br>
                            \u203a\u203a\tCustomer Relationship Management</html>""");
        }else if (letter.equals("D")) {
            lblshow.setText("""
                            <html>D<br>
                            \u203a\u203a\tDairy Technology<br>
                            \u203a\u203a\tDance<br>
                            \u203a\u203a\tDance Choreography<br>
                            \u203a\u203a\tData Entry<br>
                            \u203a\u203a\tDental Assistant<br>
                            \u203a\u203a\tDental Hygienist<br>
                            \u203a\u203a\tDental Technology<br>
                            \u203a\u203a\tDentistry<br>
                            \u203a\u203a\tDermatology<br>
                            \u203a\u203a\tDetectives/Private Investigators<br>
                            \u203a\u203a\tDisaster Management<br>
                            \u203a\u203a\tDistrict Attorney<br>
                            \u203a\u203a\tDisc Jockeying<br>
                            \u203a\u203a\tDubbing/ Voice Over</html>""");
        }else if (letter.equals("E")) {
            lblshow.setText("""
                            <html> E<br>
                            \u203a\u203a\tEcology<br>
                            \u203a\u203a\tEconomics<br>
                            \u203a\u203a\tElectrical Engineering<br>
                            \u203a\u203a\tElectrician<br>
                            \u203a\u203a\tElectrology/ Electrolysis<br>
                            \u203a\u203a\tElectronics Engineering<br>
                            \u203a\u203a\tEngineering<br>
                            \u203a\u203a\tEntomology<br>
                            \u203a\u203a\tEnvironmental Engineering<br>
                            \u203a\u203a\tEnvironmental Science<br>
                            \u203a\u203a\tEpidemiology<br>
                            \u203a\u203a\tEthical Hacking<br>
                            \u203a\u203a\tEvent Management</html>""");
        }else if (letter.equals("F")) {
            lblshow.setText("""
                            <html> F<br>
                            \u203a\u203a\tFashion Choreography<br>
                            \u203a\u203a\tFashion Designing<br>
                            \u203a\u203a\tFilm Making<br>
                            \u203a\u203a\tFinance Management<br>
                            \u203a\u203a\tFire Engineering<br>
                            \u203a\u203a\tFishery Science<br>
                            \u203a\u203a\tFitness Trainer<br>
                            \u203a\u203a\tFloriculture<br>
                            \u203a\u203a\tFood Critic<br>
                            \u203a\u203a\tFood Flavorist/Flavor Chemist<br>
                            \u203a\u203a\tFood Technology<br>
                            \u203a\u203a\tFootwear Technology<br>
                            \u203a\u203a\tForeign Language<br>
                            \u203a\u203a\tForensic Accounting<br>
                            \u203a\u203a\tForensic Science<br>
                            \u203a\u203a\tForestry/ Wildlife<br>
                            \u203a\u203a\tFragrance Chemists/ Perfumers</html>""");
        }else if (letter.equals("G")) {
            lblshow.setText("""
                        <html>G<br>
                        \u203a\u203a\tGaming Industry<br>
                        \u203a\u203a\tGastroenterology<br>
                        \u203a\u203a\tGemmology<br>
                        \u203a\u203a\tGenetic Engineering<br>
                        \u203a\u203a\tGeography<br>
                        \u203a\u203a\tGeology<br>
                        \u203a\u203a\tGeophysics<br>
                        \u203a\u203a\tGerontology<br>
                        \u203a\u203a\tGraphic Designing<br>
                        \u203a\u203a\tGraphology<br>
                        \u203a\u203a\tGynecology</html>""");
        }else if (letter.equals("H")) {
            lblshow.setText("""
                            <html>H<br>
                            \u203a\u203a\tHome Science<br>
                            \u203a\u203a\tHorticulture<br>
                            \u203a\u203a\tHospital Management<br>
                            \u203a\u203a\tHotel Management<br>
                            \u203a\u203a\tHuman Resource Management<br>
                            \u203a\u203a\tHydrotherapy</html>""");
        }else if (letter.equals("I")) {
            lblshow.setText("""
                            <html><b>I</b><br>
                            \u203a\u203a\tIAF Air Man<br>
                            \u203a\u203a\tIAF Officer<br>
                            \u203a\u203a\tICWAI (ICAI)<br>
                            \u203a\u203a\tImage Consultant<br>
                            \u203a\u203a\tIndian Air Force (IAF)<br>
                            \u203a\u203a\tIndian Army<br>
                            \u203a\u203a\tIndian Coast Guard<br>
                            \u203a\u203a\tIndian Economic/Statistical Service<br>
                            \u203a\u203a\tIndian Foreign Service<br>
                            \u203a\u203a\tIndian Navy<br>
                            \u203a\u203a\tIndian Postal Service<br>
                            \u203a\u203a\tIndian Revenue Service<br>
                            \u203a\u203a\tIndo Tibetan Border Police Force (ITBPF)<br>
                            \u203a\u203a\tIndustrial Engineering<br>
                            \u203a\u203a\tInstrumentation Engineering<br>
                            \u203a\u203a\tInsurance<br>
                            \u203a\u203a\tInsurance Underwriters<br>
                            \u203a\u203a\tIntellectual Property Attorney<br>
                            \u203a\u203a\tIntelligence Service<br>
                            \u203a\u203a\tInterior Designing<br>
                            \u203a\u203a\tInternational Business/Foreign Trade<br>
                            \u203a\u203a\tInternet of Things (IoT)<br>
                            \u203a\u203a\tInvestment Management</html>""");
        }else if (letter.equals("J")) {
            lblshow.setText("""
                            <html>J<br>
                            \u203a\u203a\tJewellery Designing<br>
                            \u203a\u203a\tJournalism / Mass Communication<br>
                            \u203a\u203a\tJudge</html>""");
        }else if (letter.equals("L")) {
            lblshow.setText("""
                            <html>L<br>
                            \u203a\u203a\tLaw<br>
                            \u203a\u203a\tLeather Technology<br>
                            \u203a\u203a\tLexicography<br>
                            \u203a\u203a\tLibrary Science<br>
                            \u203a\u203a\tLift Technology<br>
                            \u203a\u203a\tLinguistics<br>
                            \u203a\u203a\tLogistics</html>""");
        }else if (letter.equals("M")) {
            lblshow.setText("""
                            <html>M<br>
                            \u203a\u203a\tMagnetic Therapy<br>
                            \u203a\u203a\tMakeup Artist<br>
                            \u203a\u203a\tMarine Biology<br>
                            \u203a\u203a\tMarine Engineering<br>
                            \u203a\u203a\tMarketing Management<br>
                            \u203a\u203a\tMathematics<br>
                            \u203a\u203a\tMechanical Engineering<br>
                            \u203a\u203a\tMechatronics Engineering<br>
                            \u203a\u203a\tMedical<br>
                            \u203a\u203a\tMedical Laboratory Technology<br>
                            \u203a\u203a\tMedical Tourism<br>
                            \u203a\u203a\tMedical Transcription<br>
                            \u203a\u203a\tMerchant Navy<br>
                            \u203a\u203a\tMetallurgical Engineering<br>
                            \u203a\u203a\tMeteorology<br>
                            \u203a\u203a\tMicrobiology<br>
                            \u203a\u203a\tMining Engineering<br>
                            \u203a\u203a\tModelling<br>
                            \u203a\u203a\tMuseology<br>
                            \u203a\u203a\tMusic<br>
                            \u203a\u203a\tMusic Composing<br>
                            \u203a\u203a\tMusic Therapy</html>""");
        }else if (letter.equals("N")) {
            lblshow.setText("""
                            <html>N<br>
                            \u203a\u203a\tNanotechnology<br>
                            \u203a\u203a\tNational Security Guard (NSG)<br>
                            \u203a\u203a\tNaturopathy<br>
                            \u203a\u203a\tNephrology<br>
                            \u203a\u203a\tNeurology<br>
                            \u203a\u203a\tNotary<br>
                            \u203a\u203a\tNuclear Engineering<br>
                            \u203a\u203a\tNursery Teachers Training<br>
                            \u203a\u203a\tNursing<br>
                            \u203a\u203a\tNutrition and Dietetics</html>""");
        }else if (letter.equals("O")) {
            lblshow.setText("""
                            <html>O<br>
                            \u203a\u203a\tOath Commissioner<br>
                            \u203a\u203a\tOccupational Therapy<br>
                            \u203a\u203a\tOcean Engineering<br>
                            \u203a\u203a\tOceanography<br>
                            \u203a\u203a\tOenology (Wine Making)<br>
                            \u203a\u203a\tOnline Tutoring<br>
                            \u203a\u203a\tOptometry<br>
                            \u203a\u203a\tOral and Maxillofacial Surgery<br>
                            \u203a\u203a\tOrthodontics<br>
                            \u203a\u203a\tOrthopaedics<br>
                            \u203a\u203a\tOsteopathy<br>
                            \u203a\u203a\tOtolaryngology (ENT)</html>""");
        }else if (letter.equals("P")) {
            lblshow.setText("""
                            <html>P<br>
                            \u203a\u203a\tPaint Technology<br>
                            \u203a\u203a\tPainting<br>
                            \u203a\u203a\tPaleontology<br>
                            \u203a\u203a\tParamilitary Forces<br>
                            \u203a\u203a\tPatent Attorney<br>
                            \u203a\u203a\tPathology<br>
                            \u203a\u203a\tPediatrics<br>
                            \u203a\u203a\tPerfusionist<br>
                            \u203a\u203a\tPet Grooming<br>
                            \u203a\u203a\tPetroleum Engineering<br>
                            \u203a\u203a\tPharmaceutical Engineering/Technology<br>
                            \u203a\u203a\tPharmacy<br>
                            \u203a\u203a\tPhotography<br>
                            \u203a\u203a\tPhotojournalism<br>
                            \u203a\u203a\tPhotonics<br>
                            \u203a\u203a\tPhysics<br>
                            \u203a\u203a\tPhysiotherapy<br>
                            \u203a\u203a\tPisciculture<br>
                            \u203a\u203a\tPlant Pathology<br>
                            \u203a\u203a\tPlant Taxonomy<br>
                            \u203a\u203a\tPlastic Surgery<br>
                            \u203a\u203a\tPolice Services<br>
                            \u203a\u203a\tPolitical Science<br>
                            \u203a\u203a\tPolymer/Plastic Engineering<br>
                            \u203a\u203a\tPrint Technology<br>
                            \u203a\u203a\tProsthetics and Orthotics<br>
                            \u203a\u203a\tPsychiatry<br>
                            \u203a\u203a\tPsychology<br>
                            \u203a\u203a\tPublic Health<br>
                            \u203a\u203a\tPublic Prosecutor<br>
                            \u203a\u203a\tPublic Relation<br>
                            \u203a\u203a\tPurchase Management</html>""");
        }else if (letter.equals("Q")) {
            lblshow.setText("""
                            <html> Q<br>
                            \u203a\u203a\tQuality Assurance Management</html>""");
        }else if (letter.equals("R")) {
            lblshow.setText("""
                            <html>R<br>
                            \u203a\u203a\tRadio Jockey<br>
                            \u203a\u203a\tRadiography<br>
                            \u203a\u203a\tRailway Protective Force (RPF)<br>
                            \u203a\u203a\tRailway Services<br>
                            \u203a\u203a\tRailway Ticket Collector<br>
                            \u203a\u203a\tReal Estate Management<br>
                            \u203a\u203a\tReflexology<br>
                            \u203a\u203a\tRehabilitation<br>
                            \u203a\u203a\tRespiratory Therapy<br>
                            \u203a\u203a\tRetail Management<br>
                            \u203a\u203a\tRheumatology<br>
                            \u203a\u203a\tRobotics<br>
                            \u203a\u203a\tRotoscoping<br>
                            \u203a\u203a\tRubber Technology<br>
                            \u203a\u203a\tRural Management</html>""");
        }else if (letter.equals("S")) {
            lblshow.setText("""
                            <html>S<br>
                            \u203a\u203a\tSafety Management<br>
                            \u203a\u203a\tSashastra Seema Bal (SSB)<br>
                            \u203a\u203a\tScuba Diving<br>
                            \u203a\u203a\tSecurities Analysts<br>
                            \u203a\u203a\tSericulture<br>
                            \u203a\u203a\tShipping and Port Management<br>
                            \u203a\u203a\tSiddha<br>
                            \u203a\u203a\tSocial Work<br>
                            \u203a\u203a\tSociology<br>
                            \u203a\u203a\tSommelier / Wine Taster<br>
                            \u203a\u203a\tSpa/ Massage Therapy<br>
                            \u203a\u203a\tSpecial Education<br>
                            \u203a\u203a\tSpeech Pathology and Audiology<br>
                            \u203a\u203a\tSports Commentator<br>
                            \u203a\u203a\tSports Management<br>
                            \u203a\u203a\tSports/Physical Fitness<br>
                            \u203a\u203a\tStatistician<br>
                            \u203a\u203a\tStructural Engineering<br>
                            \u203a\u203a\tSugar Technology<br>
                            \u203a\u203a\tSupply Chain Management<br>
                            \u203a\u203a\tSurgical Technology<br>
                            \u203a\u203a\tSurveying</html>""");
        }else if (letter.equals("T")) {
            lblshow.setText("""
                            <html>T<br>
                            \u203a\u203a\tTaxation<br>
                            \u203a\u203a\tTea Management<br>
                            \u203a\u203a\tTeaching<br>
                            \u203a\u203a\tTechnical Trade (ITI)<br>
                            \u203a\u203a\tTechnical Writing<br>
                            \u203a\u203a\tTelecommunication Engineering<br>
                            \u203a\u203a\tTelemarketing<br>
                            \u203a\u203a\tTextile Technology<br>
                            \u203a\u203a\tThermal Engineering<br>
                            \u203a\u203a\tTour Guiding<br>
                            \u203a\u203a\tTour Operator<br>
                            \u203a\u203a\tToxicology<br>
                            \u203a\u203a\tToy Designing<br>
                            \u203a\u203a\tTrademark Attorney<br>
                            \u203a\u203a\tTransportation Engineering<br>
                            \u203a\u203a\tTravel and Tourism<br>
                            \u203a\u203a\tTrichology</html>""");
        }else if (letter.equals("U")) {
            lblshow.setText("""
                            <html>U<br>
                            \u203a\u203a\tUnani<br>
                            \u203a\u203a\tUrology</html>""");
        }else if (letter.equals("V")) {
            lblshow.setText("""
                            <html>V<br>
                            \u203a\u203a\tVeterinary Science<br>
                            \u203a\u203a\tVideo Editing<br>
                            \u203a\u203a\tVideo Jockey<br>
                            \u203a\u203a\tVirtual Assistants (VAs)<br>
                            \u203a\u203a\tVisual Merchandising<br>
                            \u203a\u203a\tVLSI/ Chip Designing</html>""");
        }else if (letter.equals("W")) {
            lblshow.setText("""
                            <html>W<br>
                            \u203a\u203a\tWeb Designing<br>
                            \u203a\u203a\tWeb Development<br>
                            \u203a\u203a\tWedding Planning<br>
                            \u203a\u203a\tWildlife/Nature Photography</html>""");
        }else if (letter.equals("Z")) {
            lblshow.setText("""
                            <html>Z<br>
                            \u203a\u203a\tZoology</html>""");
        }else{
            lblshow.setText("THERE IS NO SUCH CARRER FROM THIS LETTER...");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new ALL_CAREER_FIELDS().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ALL_CAREER_FIELDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ALL_CAREER_FIELDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ALL_CAREER_FIELDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ALL_CAREER_FIELDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ALL_CAREER_FIELDS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbletter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblshow;
    // End of variables declaration//GEN-END:variables
}
