/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package career_guidance_app;

import java.awt.Color;

/**
 *
 * @author shiva
 */
public class career_info extends javax.swing.JFrame {

    /**
     * Creates new form career_info
     */
    public career_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbintreast = new javax.swing.JComboBox<>();
        cmbsubject = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblanswer = new javax.swing.JLabel();
        lblanswer1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(198, 83));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(204, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 102));
        jLabel2.setText("PLEASE ENTER YOUR FAVOURITE SUBJECT");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 102));
        jLabel3.setText("ENTER AREA OF INTEREST");

        cmbintreast.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cmbintreast.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "TECHNICAL", "RESCARCH", "FINANCE", "POLITICAL", "VOCATIONAL" }));
        cmbintreast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbintreastActionPerformed(evt);
            }
        });

        cmbsubject.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cmbsubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "ENGLISH", "MATHS", "SCIENCE", "SOCIAL STUDYES", "DRAWING", "BIOLOGY" }));
        cmbsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsubjectActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 102));
        jButton1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("CHECK");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel4.setText("CHOOSE YOUR CAREER !!");

        lblanswer.setBackground(new java.awt.Color(204, 255, 102));
        lblanswer.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblanswer.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 153)));

        lblanswer1.setBackground(new java.awt.Color(204, 255, 102));
        lblanswer1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblanswer1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 204, 0)));

        jButton2.setBackground(new java.awt.Color(255, 0, 153));
        jButton2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 0));
        jButton2.setText("FIND COLLEGE");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblanswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(119, 119, 119)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbintreast, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(77, 110, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbsubject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbintreast, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(lblanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblanswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        String stream=(String) cmbstream.getSelectedItem();
        String subject= (String) cmbsubject.getSelectedItem();
        String interest=(String) cmbintreast.getSelectedItem();
        if ( subject.equals("SCIENCE")&&interest.equals("RESCARCH")) {
            lblanswer.setText("You are perfect for B.Sc");
            lblanswer1.setText("RECOMMENDED STREAM IS : SCIENCE ");
            lblanswer.setBackground(Color.black);
            lblanswer.setForeground(Color.red);
        } else if (subject.equals("MATHS")&&interest.equals("FINANCE")) {
            lblanswer.setText("You are perfect for B Com and C.A");
            lblanswer1.setText("RECOMMENDED STREAM IS : COMMERCE ");
            lblanswer.setBackground(Color.black);
            lblanswer.setForeground(Color.red);
        } else if (subject.equals("SOCIAL STUDYES")&&interest.equals("POLITICAL")) {
            lblanswer.setText("You are perfect for POLITICIAN And TEACHER or Other related fields");
            lblanswer1.setText("RECOMMENDED STREAM IS : ARTS ");
            lblanswer.setBackground(Color.black);
            lblanswer.setForeground(Color.red);
        }else if (subject.equals("SCIENCE")&&interest.equals("TECHNICAL")) {
            lblanswer.setText("You are perfect for ENGINEEARING FIELD");
            lblanswer1.setText("RECOMMENDED STREAM IS : SCIENCE or DEPLOMA ");
            lblanswer.setBackground(Color.black);
            lblanswer.setForeground(Color.red);
        }else if (subject.equals("DRAWING")&&interest.equals("VOCATIONAL")) {
            lblanswer.setText("You are perfect for INTERIOR DESIGNING,FASHON DESIGNING and OTHER DESIGNING FIELD's");
            lblanswer1.setText("RECOMMENDED STREAM IS : ARTS ");
            lblanswer.setBackground(Color.black);
            lblanswer.setForeground(Color.red);
        }else if (subject.equals("BIOLOGY")&&interest.equals("RESCARCH")) {
            lblanswer.setText("You are perfect for MEDICAL FIELD");
            lblanswer1.setText("RECOMMENDED STREAM IS : SCIENCE ");
            lblanswer.setBackground(Color.black);
            lblanswer.setForeground(Color.red);
        }else if (subject.equals("ENGLISH")&&interest.equals("VOCATIONAL")) {
            lblanswer.setText("You are perfect for PUBLIC SPEAKING");
            lblanswer1.setText("RECOMMENDED STREAM IS : ARTS ");
            lblanswer.setBackground(Color.black);
            lblanswer.setForeground(Color.red);
        }else if (subject.equals("DRAWING")&&interest.equals("TECHNICAL")) {
            lblanswer.setText("You are ARCHITECTURE");
            lblanswer1.setText("RECOMMENDED STREAM IS : SCIENCE ");
            lblanswer.setBackground(Color.black);
            lblanswer.setForeground(Color.red);
        }else if (subject.equals("SOCIAL STUDYES")&&interest.equals("RESCARCH")) {
            lblanswer.setText("You are ARCHEAOLOGY");
            lblanswer1.setText("RECOMMENDED STREAM IS : ARTS ");
            lblanswer.setBackground(Color.black);
            lblanswer.setForeground(Color.red);
        }else if (subject.equals("MATHS")&&interest.equals("RESCARCH")) {
            lblanswer.setText("You are MATHAMATICIAN");
            lblanswer1.setText("RECOMMENDED STREAM IS : SCIENCE ");
            lblanswer.setBackground(Color.black);
            lblanswer.setForeground(Color.red);
        }else if (subject.equals("BIOLOGY")&&interest.equals("TECHNICAL")) {
            lblanswer.setText("You are perfect for BIOMEDICAL");
            lblanswer1.setText("RECOMMENDED STREAM IS : SCIENCE ");
            lblanswer.setBackground(Color.black);
            lblanswer.setForeground(Color.red);
        }else if (subject.equals("MATHS") && interest.equals("TECHNICAL")) {
            lblanswer.setText("You are perfect for ENGINEEARING FIELD");
            lblanswer1.setText("RECOMMENDED STREAM IS : SCIENCE or DEPLOMA ");
            lblanswer.setBackground(Color.black);
            lblanswer.setForeground(Color.red);
        }
        else{
            lblanswer.setText("THERE IS NO SUCH FIELD.PLEASE TRY AGAIN");
            lblanswer.setBackground(Color.black);
            lblanswer.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbintreastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbintreastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbintreastActionPerformed

    private void cmbsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbsubjectActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new college_info().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(career_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(career_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(career_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(career_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new career_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbintreast;
    private javax.swing.JComboBox<String> cmbsubject;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblanswer;
    private javax.swing.JLabel lblanswer1;
    // End of variables declaration//GEN-END:variables
}
