/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package career_guidance_app;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shiva
 */
public class college_info extends javax.swing.JFrame {

    /**
     * Creates new form college_info
     */
    public college_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        cmbstream = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnfind = new javax.swing.JButton();
        cmbfield = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(198, 83));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(182, 76, 122));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbstream.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        cmbstream.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "SCIENCE", "COMMERCE", "ARTS" }));
        cmbstream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbstreamActionPerformed(evt);
            }
        });
        jPanel1.add(cmbstream, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\shiva\\Downloads\\photo-1607237138185-eedd9c632b0b.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 990, 160));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("PLEASE SELECT YOUR  INTERESTED STREAM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 430, 40));

        jTable1.setBackground(new java.awt.Color(255, 204, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jTable1.setForeground(new java.awt.Color(51, 51, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setDoubleBuffered(true);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 930, 280));

        btnfind.setBackground(new java.awt.Color(0, 51, 204));
        btnfind.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnfind.setForeground(new java.awt.Color(255, 204, 0));
        btnfind.setText("FIND");
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });
        jPanel1.add(btnfind, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 120, 30));

        cmbfield.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        cmbfield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT FIELD", "TECHNICAL", "NON TECHNICAL" }));
        jPanel1.add(cmbfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 140, 30));

        jButton1.setBackground(new java.awt.Color(204, 0, 204));
        jButton1.setForeground(new java.awt.Color(204, 204, 0));
        jButton1.setText("..");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbstreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbstreamActionPerformed
        // TODO add your handling code here
        String stream=(String) cmbstream.getSelectedItem();
        String field=(String) cmbfield.getSelectedItem();
        if (stream.equals("SCIENCE")) {
            cmbfield.setEnabled(true);
        }else{
            cmbfield.setEnabled(false);
        }
    }//GEN-LAST:event_cmbstreamActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        // TODO add your handling code here:
//        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
//            model.addRow(new Object[]{02201,"K.J somiya","MUMBAI"});
           String stream=(String) cmbstream.getSelectedItem();
           String field=(String) cmbfield.getSelectedItem();
        if (stream.equals("SCIENCE")&& field.equals("TECHNICAL")) {
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{02201,"RIZVI College of Enginearing","MUMBAI"});
            model.addRow(new Object[]{02202,"K.J Somiya college of Enginearing","MUMBAI"});
            model.addRow(new Object[]{02203,"Terna College of Enginearing","NAVI MUMBAI"});
            model.addRow(new Object[]{02204,"M G M's College of Enginnering","NAVI MUMBAI"});
            model.addRow(new Object[]{02205,"Pallai College of Enginnearing","NAVI MUMBAI"});
            model.addRow(new Object[]{02206,"NITIE","MUMBAI"});
            model.addRow(new Object[]{02206,"IIT BOMBAY","MUMBAI"});
            model.addRow(new Object[]{02206,"Veermata Jijabai Technological Institut (VJTI)","MUMBAI"});
            model.addRow(new Object[]{02206,"Sardar Patel College of Engineering, Andheri","MUMBAI"});
            model.addRow(new Object[]{02206,"SPCE","MUMBAI"});
            model.addRow(new Object[]{02206,"Usha Mittal Institute of Technology SNDT Women’s University","MUMBAI"});
            model.addRow(new Object[]{02206,"Institute of Chemical Technology, Matunga","MUMBAI"});
            model.addRow(new Object[]{02206,"Jawahar Education Society’s Annasaheb Chudaman Patil College of Engineering","MUMBAI"});
            model.addRow(new Object[]{02206,"Mahavir Education Trust’s Shah & Anchor Kutchhi Engineering College","MUMBAI"});
            model.addRow(new Object[]{02206,"Don Bosco Institute of Technology","MUMBAI"});
            model.addRow(new Object[]{02206,"Aldel Education Trust’s St. John College of Engineering & Management","MUMBAI"});
            
        } else if (stream.equals("SCIENCE")&&field.equals("NON TECHNICAL")) {
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{02201,"University of Mumbai","MUMBAI"});
            model.addRow(new Object[]{02202,"Ruia Autonomous College of Science and Arts.","MUMBAI"});
            model.addRow(new Object[]{02203,"St. Xavier's College (Autonomous)","NAVI MUMBAI"});
            model.addRow(new Object[]{02204,"SVKM's Mithibai College of Arts and Chauhan Institute Of Science.","MUMBAI"});
            model.addRow(new Object[]{02205,"Kishinchand Chellaram College","NAVI MUMBAI"});
            model.addRow(new Object[]{02206,"Jai Hind College","MUMBAI"});
            model.addRow(new Object[]{02207,"Sophia College (AUTONOMOUS)","MUMBAI"});
            model.addRow(new Object[]{02201,"Ramniranjan Jhunjhunwala College","MUMBAI"});
            model.addRow(new Object[]{02206,"Guru Nanak Khalsa College of Arts, Science & Commerce (Autonomous)","MUMBAI"});
            model.addRow(new Object[]{02206,"Wilson College","MUMBAI"});
            model.addRow(new Object[]{02206,"Indian Institute of Technology Bombay","MUMBAI"});
            model.addRow(new Object[]{02206,"Elphinstone College","MUMBAI"});
            model.addRow(new Object[]{02206,"SNDT Women's University","MUMBAI"});
            model.addRow(new Object[]{02206,"Kirti M. Doongursee College of Arts, Science and Commerce","MUMBAI"});
        }
        else if (stream.equals("COMMERCE")) {
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{12030,"Brihan Maharashtra College of Commerce","MUMBAI"});
            model.addRow(new Object[]{12030,"Ness Wadia College of Commerce","MUMBAI"});
            model.addRow(new Object[]{12030,"St. Mira's College For Girls","MUMBAI"});
            model.addRow(new Object[]{12030,"Marathwada Mitramandal's College of Commerce","MUMBAI"});
            model.addRow(new Object[]{12030,"Sir Parashurambhau College","MUMBAI"});
            model.addRow(new Object[]{12030,"Poona College of Arts, Science and Commerce","MUMBAI"});
            model.addRow(new Object[]{12030,"Modern College of Arts, Science and Commerce","MUMBAI"});
            model.addRow(new Object[]{12030,"Garware College Of Commerce","MUMBAI"});
            model.addRow(new Object[]{12030,"St. Vincent College Of Commerce","MUMBAI"});
            model.addRow(new Object[]{12030,"SNDT Women's University","MUMBAI"});
            model.addRow(new Object[]{12030,"Sinhgad college of commerce","MUMBAI"});
            model.addRow(new Object[]{12030,"Chandmal Tarachand Bora College","MUMBAI"});
            model.addRow(new Object[]{12030,"Abasaheb Garware College","MUMBAI"});
            model.addRow(new Object[]{12030,"Nowrosjee Wadia College ","MUMBAI"});
            model.addRow(new Object[]{12030,"Tuljaram chaturchand College e","MUMBAI"});
            model.addRow(new Object[]{12030,"Sri Shahu Mandir Mahavidyala ","MUMBAI"});
            model.addRow(new Object[]{12030,"Symbiosis College of Arts and Commercee","MUMBAI"});
            model.addRow(new Object[]{12030,"SP College Pune - Sir Parashurambhau College","MUMBAI"});
            model.addRow(new Object[]{12030,"KJ Somaiya College of Science and Commerce","MUMBAI"});
            model.addRow(new Object[]{12030,"Dr DY Patil Arts Commerce and Science College","MUMBAI"});
            model.addRow(new Object[]{12030,"St Xaviers College","MUMBAI"});
        }
        else if (stream.equals("ARTS")) {
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{12256,"St. Xavier's College (Autonomous)","MUMBAI"});
            model.addRow(new Object[]{12236,"SVKM's Mithibai College of Arts Chauhan Institute Of Science And Amrutben Jivanlal College Of Commerce And Economics","MUMBAI"});
            model.addRow(new Object[]{12256,"Jai Hind College ","MUMBAI"});
            model.addRow(new Object[]{12226,"K. J. Somaiya College Of Arts And Commerce ","MUMBAI"});
            model.addRow(new Object[]{12386,"Sophia College (AUTONOMOUS) ","MUMBAI"});
            model.addRow(new Object[]{12256,"Ramnarain Ruia Autonomous College of Science and Arts ","MUMBAI"});
            model.addRow(new Object[]{12256,"-Kishinchand Chellaram College","MUMBAI"});
            model.addRow(new Object[]{12256,"Wilson College","MUMBAI"});
            model.addRow(new Object[]{12256,"SNDT Women's University ","MUMBAI"});
            model.addRow(new Object[]{12246,"Sies College Of Arts, Science & Commerce , Santacruz","MUMBAI"});
            model.addRow(new Object[]{12296,"Elphinstone College","MUMBAI"});
            model.addRow(new Object[]{12296,"D.G. Ruparel College of Arts","MUMBAI"});
            model.addRow(new Object[]{12296,"Andrew's College of Arts","MUMBAI"});
        }
  
        
                
    }//GEN-LAST:event_btnfindActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new college_info().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();
        String stream=(String) cmbstream.getSelectedItem();
        String field=(String) cmbfield.getSelectedItem();
        URI uri = null;
        if (stream.equals("SCIENCE")&&field.equals("NON TECHNICAL")) {
            
            switch (row) {
                case 0:
                    try {
                        uri = new URI("https://mu.ac.in/");
                    } catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }       if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        } catch (IOException e) { }
                    } else { }       break;
                case 1:
                    try {
                        uri = new URI("https://www.ruiacollege.edu/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    else {  }  break;
                case 2:
                    try {
                        uri = new URI("https://xaviers.ac/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    else {  }  break;
                case 3:
                    try {
                        uri = new URI("https://mithibai.ac.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    else { /* TODO: error handling */ }
                    break;
                case 4:
                    try {
                        uri = new URI("https://kccollege.edu.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    else {  }  break;
                case 5:
                    try {
                        uri = new URI("https://www.jaihindcollege.com/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    else { /* TODO: error handling */ }
                    break;
                case 6:
                    try {
                        uri = new URI("https://sophiacollegemumbai.com/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    else { /* TODO: error handling */ }
                    break;
                case 7:
                    try {
                        uri = new URI("https://www.rjcollege.edu.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }                    
                    break;
                case 8:
                    try {
                        uri = new URI("https://www.gurunanakcollegeasc.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 9:
                    try {
                        uri = new URI("https://www.wilsoncollege.edu/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 10:
                    try {
                        uri = new URI("https://www.iitb.ac.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 11:
                    try {
                        uri = new URI("https://zollege.in/college/160573-elphinstone-college-mumbai");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 12:
                    try {
                        uri = new URI("https://sndt.ac.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 13:
                    try {
                        uri = new URI("https://kirticollege.edu.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                default:
                    break;
            }
        }else if (stream.equals("COMMERCE")) {
            switch (row) {
                case 0:
                    try {
                        uri = new URI("https://www.bmcc.ac.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 1:
                    try {
                        uri = new URI("https://nwcc.mespune.org/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 2:
                    try {
                        uri = new URI("https://www.stmirascollegepune.edu.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                
                case 3:
                    try {
                        uri = new URI("http://www.mmcc.edu.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 4:
                    try {
                        uri = new URI("https://www.spcollegepune.ac.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 5:
                    try {
                        uri = new URI("https://poonacollege.edu.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 6:
                    try {
                        uri = new URI("http://moderncollegepune.edu.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 7:
                    try {
                        uri = new URI("https://gcc.mespune.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 8:
                    try {
                        uri = new URI("http://svcpune.edu.in/web/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    else { /* TODO: error handling */ }
                    break;
                case 9:
                    try {
                        uri = new URI("https://sndt.ac.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 10:
                    try {
                        uri = new URI("http://www.sinhgad.edu/sinhgad-institutes-acs/index.html");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 11:
                    try {
                        uri = new URI("https://www.ctboracollege.edu.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 12:
                    try {
                        uri = new URI("https://garwarecollege.mespune.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 13:
                    try {
                        uri = new URI("https://nowrosjeewadia.mespune.org/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 14:
                    try {
                        uri = new URI("http://www.tccollege.org/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 15:
                    try {
                        uri = new URI("https://www.shahucollegepune.org/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 16:
                    try {
                        uri = new URI("https://www.symbiosiscollege.edu.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 17:
                    try {
                        uri = new URI("https://www.spcollegepune.ac.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 18:
                    try {
                        uri = new URI("https://kjssc.somaiya.edu.in/en");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 19:
                    try {
                        uri = new URI("https://acs.dypvp.edu.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 20:
                    try {
                        uri = new URI("https://xaviers.ac/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                default:
                    break;
            }
            
        }else if (stream.equals("ARTS")) {
            switch (row) {
                case 0:
                    try {
                        uri = new URI("https://xaviers.ac/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 1:
                    try {
                        uri = new URI("https://mithibai.ac.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 2:
                    try {
                        uri = new URI("https://www.jaihindcollege.com/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 3:
                    try {
                        uri = new URI("https://kjsac.somaiya.edu.in/en");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 4:
                    try {
                        uri = new URI("https://sophiacollegemumbai.com/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 5:
                    try {
                        uri = new URI("https://www.ruiacollege.edu/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 6:
                    try {
                        uri = new URI("https://kccollege.edu.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 7:
                    try {
                        uri = new URI("https://www.wilsoncollege.edu/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 8:
                    try {
                        uri = new URI("https://sndt.ac.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 9:
                    try {
                        uri = new URI("http://www.siesascs.edu.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 10:
                    try {
                        uri = new URI("https://collegedunia.com/college/1252-elphinstone-college-mumbai");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 11:
                    try {
                        uri = new URI("https://www.ruparel.edu/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                case 12:
                    try {
                        uri = new URI("https://standrewscollege.ac.in/");
                    }   catch (URISyntaxException ex) {
                        Logger.getLogger(college_info.class.getName()).log(Level.SEVERE, null, ex);
                    }           if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(uri);
                        }
                        catch (IOException e) { }
                    }
                    break;
                default:
                    throw new AssertionError();
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(college_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(college_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(college_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(college_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new college_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfind;
    private javax.swing.JComboBox<String> cmbfield;
    private javax.swing.JComboBox<String> cmbstream;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
